/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_POWER_SAMPLE_PB_H_INCLUDED
#define PB_POWER_SAMPLE_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _PowerSample {
    uint32_t timestamp_us;
    float energy_j;
    uint32_t duration_us;
    bool is_inference;
} PowerSample;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define PowerSample_init_default                 {0, 0, 0, 0}
#define PowerSample_init_zero                    {0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define PowerSample_timestamp_us_tag             1
#define PowerSample_energy_j_tag                 2
#define PowerSample_duration_us_tag              3
#define PowerSample_is_inference_tag             4

/* Struct field encoding specification for nanopb */
#define PowerSample_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   timestamp_us,      1) \
X(a, STATIC,   SINGULAR, FLOAT,    energy_j,          2) \
X(a, STATIC,   SINGULAR, UINT32,   duration_us,       3) \
X(a, STATIC,   SINGULAR, BOOL,     is_inference,      4)
#define PowerSample_CALLBACK NULL
#define PowerSample_DEFAULT NULL

extern const pb_msgdesc_t PowerSample_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define PowerSample_fields &PowerSample_msg

/* Maximum encoded size of messages (where known) */
#define POWER_SAMPLE_PB_H_MAX_SIZE               PowerSample_size
#define PowerSample_size                         19

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
